### ISSUE TITLE
Prepoznavanje Govora

### ISSUE THREAD

**Issue by Cabbagito** [ftn-ai-lab/sc-2022-siit#10]
Tim:
Petar Kupusarević SW57/2019

Asistent:
Dragan Vidaković

Definicija Problema:
Problem je prepoznavanje govora. Za neki audio ulaz, potrebno je prepoznati i ispisati tekst koji se govori u tom snimku.

Skup Podataka:
Dataset koji ću koristiti je [LibriSpeech ASR corpus](https://www.openslr.org/12/). Sastoji se od 360 sati (23 GB) "čistog" govora na Engleskom jeziku, gde je svaki klip ~5 sekundi. Podaci potiču od audio-knjiga sa [LibriVox-a](https://librivox.org/). Pored ovoga podaci su već segmentirani i poravnati.

Metodologija:
Radiće se fine-tuning [OpenAI](https://openai.com/) [Whisper](https://openai.com/blog/whisper/) modela nad prethodno pomenutim skupom podataka.

Evaluacija:
Metrika za ovakve probleme se obično koristi WER (word error rate). Ovo predstavlja razmeru broja grešaka i ukupnog broja reči, potiče od Levenshtein distance.
U [radu](https://arxiv.org/pdf/2212.04356v1.pdf) za Whisper je pomenuto da je zero-shot WER za clean-test skup LibriSpeech-a 2.7%, tako da ovo će da bude meta. Metriku su dobili koristeći najvećeg modela koji ima 1.55 milijardu parametara. Za moju implementaciju ću verovatno koristiti manji model. 
Pošto ću koristiti podatke za treniranje koji pripadaju istoj distribuciji kao i test podaci, i pored toga se ti podaci nisu koristili za prethodno treniranje modela, cilj će biti da performanse fine-tunovanog modela prevaziđu performanse base-modela.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Cabbagito** [comment]
https://github.com/Cabbagito/Fine-Tuning-Whisper-on-LibriSpeech
