### ISSUE TITLE
Prepoznavanje protivnika u igri CS:GO

### ISSUE THREAD

**Issue by anaandjelic** [ftn-ai-lab/sc-2022-siit#11]
Tim
---
Ana Anđelić SW14/2019

Asistent
---
Milica Škipina

Definicija problema
---
Kreiranje alata koji olakšava igranje igre Counter Strike tako što prepoznaje protivnika i na njega pozicionira nišan.

Skup podataka
---
Skup podataka ću sama kreirati upotrebom [Scutti](https://github.com/TrevorSatori/Scutti) alata koji automatski skladišti slike ekrana, a zatim uz pomoć [labelimg](https://github.com/heartexlabs/labelImg) alata obeležiti protivnike na slikama. Skup podataka će biti podeljen na trening i validacioni skup u odnosu 90:10.

Metodologija
---
1. Kreiranje skupa podataka i dodela labela
2. Treniranje YOLOv5 modela i njegovo čuvanje
3. Procesiranje frejmova u realnom vremenu i pozicioniranje nišana na protivnika

Evaluacija
---
Za evaluaciju će se koristiti precision.

GitHub repozitorijum
---
[https://github.com/anaandjelic/soft-computing-project](https://github.com/anaandjelic/soft-computing-project)

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
