### ISSUE TITLE
Klasifikacija slika na osnovu istih lica i pravljenje predikcija za pol, godine i emociju lica

### ISSUE THREAD

**Issue by teodor-sakal-franciskovic** [ftn-ai-lab/sc-2022-siit#2]
### Tim
Teodor Sakal Francišković, SW22/2019
### Asistent
Milica Škipina
### Definicija problema
Prepoznavanje ljudskih lica sa slika i njihovo grupisanje u zavisnosti od samog lica, odnosno grupisanje svih slika na kojima se nalazi jedna određena osoba u jedan direktorijum. Pravljenje predikcija za godine, pol i emocije detektovanih lica.
### Motivacija problema
Motivacija iza rešavanja ovog problema se pojavila kao potreba fotografa, koji fotografiše različite proslave, da se programski grupišu uslikane slike u različite foldere, kako se pri samom štampanju i prodavanju slika iste ne bi morale raspoređivati ručno, u zavisnosti ko se nalazi na kojoj slici.
### Skup podataka
Privatan skup podataka, par stotina slika sa venčanja.
### Metodologija
Prvobitno se učitavaju sve postojeće slike. Zatim se pomoću _MTCNN_ neuronske mreže detektuju lica sa slika. Pomoću FFT-a se vrši pretprocesiranje lica, odnosno sklanjaju se lica koja su previše _blurry_. Zatim se prolazi kroz najoštrija lica i vrši se njihovo klasterovanje sa ostalim detektovanim licima pomoću kosinusne sličnosti i _FaceNet_ neuronske mreže (posmatraju se njihovi _vector embedings_ dužine 128 brojeva, koji reprezentuju svako lice). Nakon što su lica klasterovana, vrši se upis originalnih slika po folderima u zavisnosti od lica koja se nalaze u tim slikama (za svaku sliku je zapamćeno koja lica su na toj slici pomoću rečnika). Nakon klasterovanja, detektuju se godine, pol i emocije osoba pomoću _DeepFace_-ove biblioteke (koristeći _VGG-Face_), koja vrši analizu svakog lica i u slučaju pola i godina daje konkretan rezultat predikcije, a u slučaju emocija, daje procentualnu sigurnost za svaku od emocija koje neuronska mreža podržava.
### Evaluacija
Kada je u pitanju evaluacija klasifikacije lica po folderima, nije moguće navesti konkretnu metriku jer nije poznat ukupan broj osoba, tako da će se evaluirati opisnom metrikom.
Za evaluaciju godina i pola će se koristiti _accuracy_, dok će se za evaluaciju emocija koristiti _f1 score_.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by teodor-sakal-franciskovic** [comment]
https://github.com/ColdBubbyGuy/sc-projekat
