### ISSUE TITLE
Implementacija kalkulatora na osnovu šake detektovane na video snimku

### ISSUE THREAD

**Issue by SimicAleksa** [ftn-ai-lab/sc-2022-siit#3]
**Tim**
Milica Popović, SW11/2019
Nevena Radešić, SW12/2019
Aleksa Simić, SW13/2019

**Asistent**
Milica Škipina

**Definicija problema**
Implementacija kalkulatora na osnovu videa na kom se detektuju i prepoznaju
položaji šake koji predstavljaju brojeve i računske operacije.

**Skup podataka**
Za podatke koji se odnose na cifre koristićemo [Fingers skup podataka](https://www.kaggle.com/datasets/koryakinp/fingers), a za specijalne
znakove, tj. računske operacije skup [Hand Gesture Recognition Base](https://www.kaggle.com/datasets/gti-upm/leapgestrecog). Ovi skupovi će biti
podeljeni u odnosu 80:20 na trening i testni skup i služiće za obučavanje neuronske mreže.
Za testiranje samog kalkulatora biće korišteni ručno pravljeni video snimci.

**Metodologija**
Planiramo da koristimo konvolucionu neuronsku mrežu koju ćemo istrenirati nad gore pomenutim
bazama podataka korišćenjem metoda iz Tensorflow biblioteke.
Nakon obučavanje mreže, vršiće se obrada videa. Izdvajaće se pojedinačni frejmovi
i najpre će biti odrađeno njihovo pretprocesiranje. Ono će obuhvatati pretvaranje slike
u grayscale i po potrebi njeno skaliranje, upotrebu thresholdinga i primenjivanje
morfoloških operacija. Tako obrađena slika biće ulaz u istreniranu neuronsku mrežu, a
izlaz će biti odovarajuća cifra ili aritmetički operator.
Na kraju će se vršiti izračunavanje svih dobijenih izlaza i dobijeni rezultat će biti poređen
sa očekivanim.

**Evaluacija**
Vršićemo dve vrste evaluacije: evaluacija rada neuronske mreže i kalkulatora.
Za evaluaciju neuronske mreže ćemo koristiti metriku tačnosti (accuracy) nad testnim skupom,
a za evaluaciju rada kalkulatora koristićemo takođe tačnost, ali nad ručno pravljenim skupom
podataka.

**Comment by milica-skipina** [comment]
Pošto se tim sastoji od tri člana, potrebno je da implementirate prepoznavanje cifara 0-9 i barem četiri osnovne računarske operacije (+, -, *, /). Da li je to u redu?

**Comment by SimicAleksa** [comment]
Pozdrav, u redu je.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by SimicAleksa** [comment]
https://github.com/SimicAleksa/Soft-project
