### ISSUE TITLE
Autonomna vožnja

### ISSUE THREAD

**Issue by MMomcilovic** [ftn-ai-lab/sc-2022-siit#5]
**Tim**
Miladin Momčilović SW16/2019

**Asistent**
Dragan Vidaković

**Definicija problema**
Implementacija autonomne vožnje, koja će obuhvatati praćenje linije i prepoznavanje saobraćajnih znakova i drugih vozila. 

**Skup podataka**
Kao skup podataka za prepoznavanje znakova koristiće se [BFMC-Sign-Detection](https://www.kaggle.com/datasets/arpitvaghela9210/bfmcsigndetection), kao i dodatne slike koje ću sam kreirati u simulatoru i na poligonu. Praćenje linija ne sadrži skup podataka, koristiće se realtime obrada slike sa kamere. 

**Metodologija**
Biće kreirane različite skripte za rešavanje pojedinačnih problema, koje će biti paralelizovane upotrebom ROS-a. I testirano u simulatoru i na pravom hardveru(autiću).

Za detekciju linija:
  1) Uraditi preporcessing slike
  2) Slika prolazi kroz Canny edge detection algoritam
  3) Određuje se ROI slike
  4) Primenjuje Hough transformacija
  5) Prikaz detektovanih linija
  6) Povezati sa kamerom i vršiti realtime detekciju
  7) Proslediti rezultat master thread-u za određivanje akcije
  
Za prepoznavanje znakova će se koristiti YOLOv7 koji će biti prilagođen ovom problemu i dataset-u.
  1) Uraditi preprocessing slike
  2) Proslediti modelu koji će prvobitno biti istreniran nad dataset-om
  3) Povezati sa kamerom i vršiti realtime detekciju
  4) Proslediti rezultat master thread-u za određivanje akcije
  
**Evaluacija**
Vršiću dve vrste evaluacije: evaluaciju rada mreže i detekcije linija.
Za evaluaciju mreže koristiću tačnost (accurancy) nad testnim skupom, a za evaluaciju rada praćenja linija takođe tačnost, ali nad ručno pravljenim skupom podataka.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by MMomcilovic** [comment]
[Link ka repozitorijumu.](https://github.com/MMomcilovic/Autonomous_driving)
