### ISSUE TITLE
Simulacija vožnje upotrebom NEAT algoritma

### ISSUE THREAD

**Issue by zoricavukovic** [ftn-ai-lab/sc-2022-siit#6]
**Tim**
Jovan Jovančević SW 01/2019
Zorica Vuković SW 21/2019

**Asistent**
Milica Škipina

**Definicija problema**
Potrebno je napraviti sistem koji će naučiti na koji način vozila treba da se kreću po 2D mapi kako ne bi sišli sa iste. Takođe je potrebno detektovati i koliziju između automobila ukoliko do toga dođe.

**Skup podataka**
Za kretanje vozila po mapi, korišćen je ručno kreiran skup 2D mapa iz ptičije perspektive pri čemu su staze na mapama različite težine.

**Metodologija**
Biće kreirana PyGame aplikacija koja se sastoji iz dve faze. 
- Prva je učenje vozila da se kreću po mapi bez izlaska sa staze uz korišćenje NEAT algoritma. Detekcija samog puta od ostatka slike će biti realizovana uz pomoć morfoloških operacija za obradu slike (OpenCV biblioteka). Izlaz iz ove faze će biti najbolje istrenirana (winner) jedinka u poslednjoj generaciji.
- Ulaz u drugu fazu su dve winner jedinke koje se ispravno kreću po stazi na različit način, pa je zbog toga moguća njihova međusobna kolizija. Detekcija kolizije će biti odrađena na dva načina:
   - auto kojim upravljamo nema nikakvo znanje o poziciji drugog auta na mapi, pa se detekcija vrši samo na osnovu morfološke obrade slike;
   - auto zna poziciju drugog auta na mapi, pa je auto već u startu detektovan i kolizija se može jednostavno utvrditi (ovaj način je ostavljen kako bi se prikazalo kretanje vozila u punoj brzini).
 
**Evaluacija**
Metrika evaluacije biće količnik pređenog puta i vremena, pri čemu će za svaku mapu biti postavljen isti broj generacija za treniranje.

**GitHub repozitorijum**
https://github.com/jovancevic123/self-driving-cars-NEAT

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by jovancevic123** [comment]
https://github.com/jovancevic123/self-driving-cars-NEAT
