### ISSUE TITLE
Detekcija i klasifikacija RSD kovanica

### ISSUE THREAD

**Issue by milsek** [ftn-ai-lab/sc-2022-siit#8]
#### Tim
Dejan Dopuđ SW25/2019
Milan Sekulić SW54/2019

#### Asistent
Milica Škipina

#### Definicija problema
Određivanje ukupne zbirne vrijednosti više različitih dinarskih kovanica sa fotografije.

#### Motivacija problema
Ljudi u Srbiji često skupljaju velike količine kovanica koje same po sebi ne vrijede mnogo. Nakon akumulacije određene količine, određivanje zbirne vrijednosti tog novca postaje problem koji oduzima dosta vremena. Cilj ovog projekta je da ljudima olakša i ubrza taj proces uz pomoć mašinskog učenja.

#### Skup podataka
- **_Skup podataka za treniranje_** ćemo konstruisati sami tako što ćemo napraviti više fotografija različitih kovanica za svaku vrijednost zbog razlika u boji samih kovanica, uz različito osvjetljenje, na tamnoj pozadini i licem okrenutim ka gore. Dodatno ćemo programski rotirati svaku od fotografija više puta oko centra kako bismo proširili skup podataka i omogućili mreži da prepoznaje kovanice bez obzira na rotaciju. Anotacije će sadržati vrijednost kovanice.
- **_Skup podataka za testiranje_** ćemo stvoriti tako što ćemo napraviti fotografije koje će sadržati veći broj različitih kovanica na tamnoj pozadini licem okrenutim ka gore. Anotacije će sadržati broj i ukupnu vrijednost svih kovanica na fotografiji.

#### Metodologija
1. Thresholding za razdvajanje objekata od interesa (kovanica) od pozadine
2. Detekcija ivica za lociranje i prebrojavanje pojedinačnih kovanica
3. Neuronska mreža za klasifikaciju kovanica

#### Evaluacija
Evaluacija se sastoji iz dva dijela:
1. **_Evaluacija algoritma za detekciju kovanica_**
Test podaci će za svaku sliku sadržati broj kovanica na njoj, algoritam treba uspješno da ih prebroji uz što manji MAE.
2. **_Evaluacija algoritma za klasifikaciju i određivanje ukupne zbirne vrijednosti kovanica_** 
Test podaci će za svaku sliku sadržati zbir vrijednosti kovanica na njoj, algoritam treba uspješno da ih klasifikuje i odredi ukupnu zbirnu vrijednost istih uz što manji MAE.

Link: https://github.com/DejanDopudj/coin-detection-classification

**Comment by milica-skipina** [comment]
Nedostaju podaci o asistentu.

**Comment by milsek** [comment]
> Nedostaju podaci o asistentu.

Izvinjavam se na propustu, podatak je sada dodat.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
