### ISSUE TITLE
Detekcija lica i praćenje pogleda

### ISSUE THREAD

**Issue by Aksont** [ftn-ai-lab/sc-2022-siit#9]
**Tim:**
Đorđević Mihajlo sw34/2019
Stanivuk Aleksa sw29/2019

**Asistent:** Milica Škipina

**Definicija problema:** _Realtime_ detekcija lica i praćenje pogleda i detekcija treptanja, ukoliko je prethodno prepoznato da postoji lice.

**Motivacija:** Osobe sa otežanom ili onemogućenom koordinacijom pokreta ruku bi na ovaj način mogle da upravljaju računarom bez potrebe da koriste miš ili druge upravljačke hardverske uređaje, već samo kameru.

**Metodologija:**	
Obrada videa pomoću _opencv_ biblioteke
Detekcija lica pomoću neuronske mreže korišćenjem _tensorflow_-a
Detekcija očiju pomoću _facial mark points_-a (_dlib_ biblioteka)
Detekciju treptanja 
Detekcija pogleda (kuda su oči usmerene)
Primena _thresholding_-a radi razdvajanja zenice i irisa od ostatka 
Manipulacija okruženjem i izdvojenom zonom od interesa radi dobijanja preciznijih informacija

**Evaluacija:** Performanse će se evaluirati postavljanjem u odnos uspešno detektovanih željenih pogleda (i treptanja) sa ukupnim brojem usmerenih pogleda (i treptanja).  Pošto je _realtime_ detakcije, korisnik ima mogućnost da odabere koji je “pokret” uradio i time se proverava da li je sistem uspešno ili pogrešno izvršio detekciju.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by mihajlodj** [comment]
https://github.com/mihajlodj/soft-project
